# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CourseConnect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CourseConnect

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Messaging'

  target 'CourseConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CourseConnectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
